### ISSUE TITLE
How do you planet money tree's

### ISSUE THREAD

**Issue by MasterSara85** [SirBeethoven/LeafHacks#1]

**Comment by MasterSara85** [comment]
how does the cheat work or does it even work

**Comment by SirBeethoven** [comment]
Oof, I forgot how to do this. Usually seeder works, otherwise, you could bury a money bag with a golden shovel (and you might have to water it with a golden watering can). I hope that this helps, even though I'm replying months late. Please open up a new issue if this doesn't help.
